default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Run tests"
  lane :tests do
    run_tests(
      workspace: "KotlinMultiplatformTemplate.xcworkspace",
      scheme: "KotlinMultiplatformTemplate"
    )
  end
end
